name: Build, push, and deploy image
on:
  push:
    branches: ["main"]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install modules
        run: yarn install

      - name: Run tests
        run: yarn test